### ISSUE TITLE
Farm Tool - Hoe

### ISSUE THREAD

**Issue by LiamAnd** [UQcsse3200/2023-studio-1#17]
# **Implementation of Farm Tool - Hoe**
**Task:** [Task Name](#3).
**Feature:** [Adding Farm Tools Enhancement](#7 )

The Hoe is a farming tool that the player will use to interact with the environment, allowing users to till the ground to then plant their crops. Through the use of the [Base Tool Entity](#13 ), the hoe farming tool will be implemented into the game and will contain basic functionality to ensure desired results. Expected outcome of this task include, being able to view the hoe sprite alongside the player and user input that the player to environment interaction.

# **Dependencies**

- [ ] Base Tool Factory (#13)
- [ ] Hoe Sprite (#12)
 
# **Milestones**

- [ ] Hoe Implemented (Aug. 26)
 
**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Liam Anderson (@LiamAnd)
- Shanon Lakshan Chandrasekara (@86LAK)

**Comment by 86LAK** [comment]
@LiamAnd not sure what the latest commit on hoe-farm-tool is meant to do. We shouldn't be setting the hoe to just equal the players position.

**Comment by 86LAK** [comment]
closing this ticket as the functionality of it will be included in the new design within the tool component. #51
