### ISSUE TITLE
Bug when in terminal

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#181]
## Description
When the player is moving in a direction and in the command line, letting go of that key will cause the player to walk in that direction forever.

## How To Reproduce
Steps to reproduce the behaviour:
1. Hold a direction to move (WASD)
2. Click [F1]
3. Let go of the direction

## Expected Behaviour
Stop moving when you let go or when entering the command line

## Temporary Fix
Just don't do what I said above?

**Comment by lucashicks1** [comment]
Okay I'll have a look into this. The Debug Terminal was given in the base game engine so I'll have to have a proper look and see how it's triggered.

**Comment by JTrenerry** [comment]
any progress?

**Comment by lucashicks1** [comment]
> any progress?

Not yet, haven't looked into it much. Will have a look today.

**Comment by lucashicks1** [comment]
I've had another look at the Terminal trying to stop player/tractor movement and can't think of a smart way to do it without making the `KeyboardTerminalInputComponent` and the `TouchTerminalInputComponent` super messy, and the way that the player and tractor are coupled. Also the added code has broken the tests as the components now have to access the player from the `GameArea` and this is not initialised in the tests. I will have a look at this next sprint if possible as this is an issue with the provided game engine and not my implementation of various commands.

**Comment by JTrenerry** [comment]
Fixed

**Comment by JTrenerry** [comment]
Failing terminal tests due to no GameArea, adding mock now (never done this before so might be a bit)
