### ISSUE TITLE
Game Lag after 15mins

### ISSUE THREAD

**Issue by 86LAK** [UQcsse3200/2023-studio-1#233]
## Description
After 15 or so mins game becomes unplayable and drops to 1fps 

## How To Reproduce
Steps to reproduce the behaviour:
1. New game. wait 15mins 

## Expected Behaviour
Not go to 1ps

## Temporary Fix
Be really good and finish game <15mins

**Comment by JTrenerry** [comment]
When updating the display it was creating two to three new Images and a new table and a new group, which is obviously very intense on the computer, so changed to using an Array to store them and just calling the correct one. This happened both for the time display and weather display, may be others that do this so please ensure other bits of code are not creating the same Textures over and over again when they can be reused as is done here.
