### ISSUE TITLE
Inventory / Toolbar Display refresh causing significant lag

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#243]
## Description
Whenever the inventory / toolbar is update it resets the toolbar which causes a noticable lag for the user.

## How To Reproduce
Steps to reproduce the behaviour:
1. Modify inventory in any way

## Expected Behaviour
No lag should be present for such an act

## Screenshots
Nill.

## Additional Context
Nill.

## Temporary Fix
Nill.

**Comment by tristanduncombe** [comment]
I've been working towards fixing this. I think the correct approach may be not keep creating itemSlots but rather update them. I wrote some code which I thought would get closer, but it doesn't re-render correctly. I don't exactly know why but it's too large an issue for tomorrow.

`private void resetInventory(){
    Array<Cell> cells = table.getCells();

    for (int i = 0; i < 30; i++) {
      ItemSlot itemSlot = (ItemSlot) cells.get(i).getActor();
      Entity itemEntity = playerInventory.getItem(new Point(i / 10, i % 10));

      if (itemEntity != null) {
        ItemComponent item = itemEntity.getComponent(ItemComponent.class);
        itemSlot.setTexture(item.getItemTexture());
        int count = playerInventory.getItemCount(itemEntity);
        itemSlot.setCount(count);
      }
      table.invalidate();
    }
    table.layout();
    stage.act();
    stage.draw();
  }`
  
  (Bing helped me to generate this code)

**Comment by tristanduncombe** [comment]
Perhaps, we could modify the the event to send what specific changes they were and only modify those cells as well? This should reduce complexity.

**Comment by lucashicks1** [comment]
> Perhaps, we could modify the the event to send what specific changes they were and only modify those cells as well? This should reduce complexity.

This makes sense. Could you have an 'updateToolbar' event which the toolbar component listens to, then when a change is made to the toolbar, it fires that event, providing the slot number and the item itself.

**Comment by tristanduncombe** [comment]
> 

Yeah that's what I'm thinking. I'll look into it after Wednesday.
