### ISSUE TITLE
Disable player actions/pause game when in quests menu

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#250]
# **Description**
**Feature:** #135 

With the current implementation of the quest NPC, the player is able to move around the game world whilst the quest menu is open. As a result, the player can move far away from the NPC with the window still showing. The player must navigate back to the NPC to close it with half of the game screen being blocked. 

## Desired Implementation
- Pause the game entirely when the window is open (depends on team 5 for pause functionality + team 7 time system)

### Alternative Implementation
- Automatically close the window when the player moves too far away from the NPC
 
# **Milestones**
Ideal implementation depends on pause functionality being implemented & merged into main
- [x] Quick fix implemented (Sep. 12)
- [ ] Proper pause implementation done (Sep. 13 - dependant on pause)
 
**Completion Deadline:** Sep. 13

# **Documentation**
- [Mission UI](../wiki/Mission-UI)
 
# **Member**

**Comment by vilnor** [comment]
Closed by #613
