### ISSUE TITLE
Main broken due to Tobacco Seed

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#282]
## Description
Currently main is broken due to a broken file path of tobacco seeds.

## How To Reproduce
Steps to reproduce the behaviour:
1. Create new game or continue game
2. Game crashes and produces error "com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: images/plants/tobacco_seed.png"

## Expected Behaviour
The game shouldn't crash while continuing or loading the game.

## Temporary Fix
Describe any known workaround for the problem.

**Comment by 86LAK** [comment]
Temporary Fix = dont play game :)

**Comment by JTrenerry** [comment]
Adding those who may be responsible / contributed to plants / seeds

**Comment by tristanduncombe** [comment]
I've identified and fixed the problem. It stemmed from a broken path in createCowFood.
