### ISSUE TITLE
Items still get picked up when inventory is full

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#308]
## Description
Items still get picked up from the player and disappear from the world even when the inventory is full.

## How To Reproduce
Steps to reproduce the behaviour:
1. Fill your inventory up with items, (use `addItem` command or just add items directly to inventory via code)
2. Walk over an item to pick it up
3. Watch the item disappear and not added to inventory even though it is full

## Expected Behaviour
Item should not be picked up when inventory is full.

## Temporary Fix
Add a getter in the `InventoryComponent` called `isFull()` which returns a boolean. Then in the `ItemPickUpComponent` you would access this method in the `InventoryComponent` and decide whether to pick up the item. To allow for inventories with different capacities, you could also overload the constructor and let someone pass in a max number of items. If inventory is rendered dynamically this would be fine because it should hopefully (not sure how you're rendering inventory) calculate the rows and columns based on number of inventory slots and then just draw them.

**Comment by tristanduncombe** [comment]
Should be easy to implement. Thanks for reporting!

**Comment by nimeshgarg** [comment]
#467
