### ISSUE TITLE
Misc Tasks

### ISSUE THREAD

**Issue by JTrenerry** [UQcsse3200/2023-studio-1#343]
**Task:** Changing player hitbox size and setting time to start at 6am.
**Feature:** N/A

The player cannot currently fit between two tiles and as such their hitbox size should be slightly reduced in order to fit through objects like gates or in-between chests. On top of this, the game should most likely not start at 12am and as such will be moved to 6am, this is not final and should be changed later, just being proactive with it so that I can see when debugging the game.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Sep. 18) - Change player collider size
- [x] Step 2 (Sep. 18) - Change start time
 
**Completion Deadline:** Sep. 19

# **Member**
- Jackson Trenerry @JTrenerry

**Comment by lucashicks1** [comment]
In regards to the start time, I think the constructor should set the hour to 6, plus it would be useful for implementing the bed. Let me make some changes and I'll push to this branch.

**Comment by JTrenerry** [comment]
> In regards to the start time, I think the constructor should set the hour to 6, plus it would be useful for implementing the bed. Let me make some changes and I'll push to this branch.

probably just did not want to edit the code too much, but since I think your time made it / had a hand feel free to change it. Or even take in a value constructor.

**Comment by lucashicks1** [comment]
> > In regards to the start time, I think the constructor should set the hour to 6, plus it would be useful for implementing the bed. Let me make some changes and I'll push to this branch.
> 
> probably just did not want to edit the code too much, but since I think your time made it / had a hand feel free to change it. Or even take in a value constructor.

Just changed it and fixed the `setHour()` method. Added a `setMorningTime()` command which team implementing bed could use (not sure whether it's best to have this in-built in `TImeService` or let them implement it). Will also have to add testing for the `TimeService` class.

**Comment by JTrenerry** [comment]
> > > In regards to the start time, I think the constructor should set the hour to 6, plus it would be useful for implementing the bed. Let me make some changes and I'll push to this branch.
> > 
> > 
> > probably just did not want to edit the code too much, but since I think your time made it / had a hand feel free to change it. Or even take in a value constructor.
> 
> Just changed it and fixed the `setHour()` method. Added a `setMorningTime()` command which team implementing bed could use (not sure whether it's best to have this in-built in `TImeService` or let them implement it). Will also have to add testing for the `TimeService` class.

for the bed could just speed up time instead so you can get input of the sun going up and down and all that

**Comment by lucashicks1** [comment]
> > > > In regards to the start time, I think the constructor should set the hour to 6, plus it would be useful for implementing the bed. Let me make some changes and I'll push to this branch.
> > > 
> > > 
> > > probably just did not want to edit the code too much, but since I think your time made it / had a hand feel free to change it. Or even take in a value constructor.
> > 
> > 
> > Just changed it and fixed the `setHour()` method. Added a `setMorningTime()` command which team implementing bed could use (not sure whether it's best to have this in-built in `TImeService` or let them implement it). Will also have to add testing for the `TimeService` class.
> 
> for the bed could just speed up time instead so you can get input of the sun going up and down and all that

Oh yeah I like that idea more
