### ISSUE TITLE
Inventory Rework

### ISSUE THREAD

**Issue by nimeshgarg** [UQcsse3200/2023-studio-1#376]
# **Description**
 Currently Inventory and InventoryDisplay have a significant amount of needed functionality missing or needs to be improved to resolve current issues. This feature encompasses improving the inventory system as a whole to the growing needs of the game and to improve the overall user experience. This feature should allow more functionality across the application, such as a chests and perishable items.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #243 (Oct. 1)
- [x] #378 (Oct. 2)
- [x] #320 (Oct. 2)

**Completion Deadline:** Oct. 3

# **Documentation**

# **Members**
- Nimesh(@nimeshgarg) 
- Tristan (@tristanduncombe)

**Comment by JTrenerry** [comment]
What is the progress looking like sir

**Comment by nimeshgarg** [comment]
InventoryComponent rework is complete. Working on the display components

**Comment by tristanduncombe** [comment]
All merged.
