### ISSUE TITLE
Shovel, croptile, terraintile interaction bug

### ISSUE THREAD

**Issue by DonghyugDavidJeong** [UQcsse3200/2023-studio-1#419]
## Description
Shovel behaviour not working as intended.

## How To Reproduce
Steps to reproduce the behaviour:
1. Create Croptile
2. Plant seed in Croptile
3. Use shovel on Croptile
4. See error - the texture of croptile becomes un-interactable, another croptile can be created on top of it, croptile cannot be destroyed.

## Expected Behaviour
CropTile should be able to be interacted with, even after shovelling a croptile with a plant on it.

## Temporary Fix
Do not shovel a croptile that has a plant on it.

**Comment by DonghyugDavidJeong** [comment]
Bug fixed in mission-system branch.

**Comment by vilnor** [comment]
This seems to still exist in main, I'm going to reopen it.
