### ISSUE TITLE
Add inventory quests

### ISSUE THREAD

**Issue by tristanduncombe** [UQcsse3200/2023-studio-1#575]
# **Description**
**Task:** [Add inventory quests](#575).
**Feature:** [Complete inventory](#567)

To further enable gameplay, it would be nice to add quests to encourage further gameplay. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Identify relevant quests (Oct. 09)
- [x] Implement relevant quests (Oct. 10)
 
**Completion Deadline:** Oct. 10

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by tristanduncombe** [comment]
I think the quests will be along the lines of "collect x items" or like "collect in total 100 items", although these might not be satisfactory, if nothing can be identified then the ticket will be closed

**Comment by tristanduncombe** [comment]
Perhaps this should be an achievement rather than a quest

**Comment by adamFittlerUQ** [comment]
Have implemented a collect x items quest will talk with quest team in class tomorrow to build further on it.
