### ISSUE TITLE
Crash on Switch to Empty Item Near Tamed Cow

### ISSUE THREAD

**Issue by bunnyycat** [UQcsse3200/2023-studio-1#587]
## Description
The game crashes upon switching to an empty item slot after taming a cow (still being in range of the cow)

## How To Reproduce
Steps to reproduce the behaviour:
1. Complete quests from the beginning up until starting the taming quest as normal
2. Hold corn, find a cow and tame it
3. Switch to an empty item slot while still near the cow

## Expected Behaviour
The game to not crash

## Temporary Fix
Don't tame any cows

**Comment by UniversalTze** [comment]
Fixed
