### ISSUE TITLE
Fish Art for Fishing

### ISSUE THREAD

**Issue by bunnyycat** [UQcsse3200/2023-studio-1#596]
# **Description**
**Task:** Fish art
**Feature:** #582 - #544 

This ticket is for the art assets for all fish sprites (any number is ok).

# **Milestones**
List of steps that need to be completed for this task.
- [x] At least 5 fish done (October 9)
- [ ] Any more fish (October 11)
 
**Completion Deadline:** October 12
 
# **Documentation**
- Fish https://github.com/UQcsse3200/2023-studio-1/wiki/Fish
 
# **Member**
- Ali (@bunnyycat)

**Comment by JTrenerry** [comment]
This finished?

**Comment by bunnyycat** [comment]
> This finished?

yep
