### ISSUE TITLE
Improve project `README`

### ISSUE THREAD

**Issue by lucashicks1** [UQcsse3200/2023-studio-1#627]
# **Description**
**Task:** Improving project `README.md`

This task is for improving the current project README from the one given at the start of the project. This may require involvement from several teams as ideally, the README should give a basic overview of the game.

# **Member**
- Lucas Hicks (@lucashicks1) Lucas Hicks

**Comment by JTrenerry** [comment]
imo all the read me needs is something small from each team and the entirety of DJ Khaled's discography.

**Comment by 86LAK** [comment]
ngl i was planning on sneaking some random stuff into the readme
