### ISSUE TITLE
WateringCan Water Level Management

### ISSUE THREAD

**Issue by LiamAnd** [UQcsse3200/2023-studio-1#66]
# **Description**
Implement the Watering-Can level component that will manage and update the water that can be carried within the watering-can as apart of the farming tools #51. It will contain two key variables, MaxCapacity and CurrentWaterLevel, and the supporting functions to update these values. Along with all unit testing for this component file to ensure reliability.
 
**Completion Deadline:** Aug. 28

# **Milestones**
- [x] Watering-can level component
- [x] Unit tests
 
# **Member**
Liam Anderson (@LiamAnd)

**Comment by 86LAK** [comment]
done
