### ISSUE TITLE
NullPointerException thrown when clicking outside the map

### ISSUE THREAD

**Issue by 27abdullah** [UQcsse3200/2023-studio-1#97]
## Description
A NullPointerException is thrown when standing adjacent to map edge and clicking outside the map. Also occurs when clicking in the tractor.

## How To Reproduce
Case 1:
1. Move to map edge
2. Click outside the map

Case 2:
1.  Enter the tractor
2. Click anywhere

## Expected Behaviour
Clicking outside the map should do nothing. Clicking inside the tractor should not crash the game.

## Screenshots

<img width="1106" alt="image" src="https://github.com/UQcsse3200/2023-studio-1/assets/98884418/950afa41-54e0-4ece-803a-32da0cab11a4">

**Comment by 86LAK** [comment]
ez fix just dont click when in tractor 😎 . kidding will have a look now

**Comment by JTrenerry** [comment]
we (team 1) can only fix the tractor one, should be up in about 5 minutes, the map one we cannot.

**Comment by JTrenerry** [comment]
Tractor side fixed, just map side now.

**Comment by 86LAK** [comment]
https://github.com/UQcsse3200/2023-studio-1/pull/101
fixed our end, map thing requires Team 3

**Comment by RileyWhitty** [comment]
We are still working on trying to get this function to work and will do a pull request when we believe it is working on our end

**Comment by RileyWhitty** [comment]
Do we know large the game area is in pixels or whatever unit we are using to measure the x,y coordinate of the player/ mouse pointer?
